# Generated by Django 3.1.2 on 2020-10-11 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('desc', models.TextField(default='This is the default description content in the description field')),
                ('dateposted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
