# Generated by Django 3.1.2 on 2020-10-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='shop_images'),
        ),
    ]
